### ISSUE TITLE
Got 401 after deploying on Azure App Service

### ISSUE THREAD

**Issue by askpramod** [Azure-Samples/app-service-msi-keyvault-node#4]
### Minimal steps to reproduce
> Follow all steps from the README file

### Any log messages given by the failure
> Yes, after completing all mentioned steps, i below json output on browsing apps root "/"
Output:
{
  "statusCode": 401,
  "request": {
    "rawResponse": false,
    "queryString": {},
    "url": "https://yozan.vault.azure.net/secrets/secret/?api-version=2016-10-01",
    "method": "GET",
    "headers": {
      "Content-Type": "application/json; charset=utf-8",
      "x-ms-client-request-id": "bf93613f-4e73-4794-ae9e-676d3429420d",
      "accept-language": "en-US",
      "user-agent": "Node/v10.14.1 (ia32-Windows_NT-10.0.14393) ms-rest/2.3.0 ms-rest-azure/2.5.2 azure-keyvault/3.0.0-preview Azure-SDK-For-Node"
    },
    "body": null
  },
  "response": {
    "body": "",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "expires": "-1",
      "server": "Microsoft-IIS/10.0",
      "www-authenticate": "Bearer authorization=\"https://login.windows.net/e5aa43c7-d783-4a78-9a79-616d713556c2\", resource=\"https://vault.azure.net\"",
      "x-ms-keyvault-region": "centralindia",
      "x-ms-request-id": "799e79f6-d0e2-4394-9441-6484f05fb4aa",
      "x-ms-keyvault-service-version": "1.1.0.859",
      "x-ms-keyvault-network-info": "addr=52.172.204.196;act_addr_fam=InterNetwork;",
      "x-aspnet-version": "4.0.30319",
      "x-powered-by": "ASP.NET",
      "strict-transport-security": "max-age=31536000;includeSubDomains",
      "x-content-type-options": "nosniff",
      "date": "Wed, 26 Dec 2018 16:17:41 GMT",
      "connection": "close",
      "content-length": "0"
    },
    "statusCode": 401
  }
}

### OS and Version?
> Ubuntu 16.04

### NodeJs Versions
> v10.14.2

Please help me resolve this ASAP.

Thanks,
Pramod

**Comment by beth-panx** [comment]
Having the same problem here.

**Comment by Shell32-Natsu** [comment]
Add `{"resource": "https://vault.azure.net"}` parameter to the function `loginWithAppServiceMSI`.

Note: `https://vault.azure.net/` doesn't work...
