### ISSUE TITLE
Error: ECONNREFUSED on deploying the NodeJs App on a VM

### ISSUE THREAD

**Issue by askpramod** [Azure-Samples/app-service-msi-keyvault-node#5]
### Minimal steps to reproduce
> Follow all steps from the README file BUT replace App Service with a VM (create one for this purpose) and enable the VM for MSI and add an access policy that grants the VM access to Get Secrets.

### Any log messages given by the failure
> Yes, after completing all mentioned steps, i got error on browsing root "/"
Error:
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50342}

### OS and Version?
> Ubuntu 16.04
### NodeJs Versions
> v10.14.2

Please help me resolve this ASAP. I am using msRestAzure.loginWithVmMSI(). My server.js is attached.
[server.js.zip](https://github.com/Azure-Samples/app-service-msi-keyvault-node/files/2710536/server.js.zip)

Thanks,
Pramod

**Comment by fdescamps** [comment]
Hi,

Did you find the solution ?

A+

**Comment by jongio** [comment]
This should be resolved.  Please reopen if you are able to reproduce.  Thanks
